In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
sns.set_style("whitegrid")
sns.set_palette("GnBu_d")
import folium
from folium import plugins
from folium.plugins import HeatMap
from datetime import datetime
from datetime import timedelta
import math
import random 
import timeit

In [2]:
BRM = pd.read_csv("bremen.csv")
BRM.describe()

,b_number,orig_lat,orig_lng,dest_lat,dest_lng
count,157576.000000,157576.000000,157576.000000,157576.000000,157576.000000
mean,20756.695740,53.078790,8.820687,53.078752,8.821165
std,138.453222,0.015147,0.031008,0.015502,0.031926
min,20507.000000,52.212258,7.798486,51.938120,7.594058
25%,20635.000000,53.072058,8.801587,53.071972,8.801635
50%,20765.000000,53.078923,8.813120,53.078836,8.813507
75%,20875.000000,53.084751,8.834999,53.084880,8.836207
max,20999.000000,53.829893,9.077380,53.803267,10.718158

In [3]:
FRB = pd.read_csv("freiburg.csv")
FRB

,day,time,b_number,city,trip_duration,orig_lat,orig_lng,dest_lat,dest_lng
0,2019-05-06,14:22:00,32560,freiburg,0 days 00:07:00.000000000,47.993178,7.795708,47.994027,7.796084
1,2019-05-07,10:42:00,32560,freiburg,0 days 00:07:00.000000000,47.994191,7.796853,47.991960,7.797405
2,2019-05-07,11:02:00,32560,freiburg,0 days 00:09:00.000000000,47.992044,7.797352,47.992000,7.797478
3,2019-05-07,12:48:00,32560,freiburg,0 days 00:23:00.000000000,47.992107,7.797499,47.994271,7.796668
4,2019-05-08,09:00:00,32560,freiburg,0 days 00:03:00.000000000,47.994178,7.796721,47.992307,7.796708
...,...,...,...,...,...,...,...,...,...
127524,2020-01-20,08:14:00,32999,freiburg,0 days 00:12:00.000000000,48.012050,7.854987,47.994729,7.846862
127525,2020-01-20,09:10:00,32999,freiburg,0 days 00:04:00.000000000,47.996100,7.846160,48.000858,7.849587
127526,2020-01-20,10:03:00,32999,freiburg,0 days 00:24:00.000000000,48.000858,7.849587,48.002664,7.851253
127527,2020-01-20,13:55:00,32999,freiburg,0 days 00:07:00.000000000,48.002664,7.851253,47.997430,7.842500
127528,2020-01-20,14:16:00,32999,freiburg,0 days 00:18:00.000000000,47.997430,7.842500,48.013770,7.807080

In [24]:
FRB_bikes = FRB["b_number"].unique()
FRB_bike1 = FRB.loc[FRB["b_number"] == 32560]

In [47]:
FRB_heat_map = folium.Map(location=(47.993178, 7.795708),  tiles='Stamen Toner', 
                       zoom_start=15, control_scale=True, max_zoom=20)

FRB_bike1_coordinates = [FRB_bike1["orig_lat"],FRB_bike1["orig_lng"]]

HeatMap(FRB_bike1_coordinates).add_to(FRB_heat_map)
folium.CircleMarker(radius=5, location=(FRB_bike1["orig_lat"],FRB_bike1["orig_lng"]), popup='The Waterfront', 
                                 color='crimson', fill_color='crimson').add_to(FRB_heat_map)

FRB_heat_map

ValueError: Location should consist of two numerical values, but 0      47.993178
1      47.994191
2      47.992044
3      47.992107
4      47.994178
         ...
323    47.999870
324    47.995016
325    47.976160
326    47.992394
327    47.982453
Name: orig_lat, Length: 328, dtype: float64 of type <class 'pandas.core.series.Series'> is not convertible to float.